CREATE TABLE UserMemory (
  memoryId  UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  userId    UNIQUEIDENTIFIER NOT NULL,
  content   NVARCHAR(MAX)   NOT NULL,
  createdAt DATETIME2       NOT NULL DEFAULT GETDATE(),
  updatedAt DATETIME2       NOT NULL DEFAULT GETDATE()
);
GO
